chartpdf/urls.py
from django.urls import path

from . import views

app_name = "chartpdf"
urlpatterns = [
    path("api/points.json", views.api_get_points, name="api_get_points"),
    path(
        "django_scatter.svg",
        views.django_scatter_svg,
        name="django_scatter_svg",
    ),
    path("", views.index),
]

proj/urls.py
# from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("chartpdf.urls")),
    # path("admin/", admin.site.urls),
]

chartpdf/views.py
import random

import javascript
from django.http import JsonResponse
from django.shortcuts import render
from django.template import loader
import subprocess


def get_points(count=None, seed=None):
    if count is None:
        count = 800
    else:
        count = min(max(0, count), 10_000)

    if seed is not None:
        random.seed(seed)

    return [
        {"x": random.gauss(0.5, 0.3), "y": random.gauss(0.5, 0.2)}
        for _ in range(count)
    ]


def get_params(GET):
    try:
        count = int(GET["count"])
    except (KeyError, ValueError):
        count = None

    try:
        seed = int(GET["seed"])
    except (KeyError, ValueError):
        seed = None

    return count, seed


def api_get_points(request):
    count, seed = get_params(request.GET)

    return JsonResponse({"points": get_points(count, seed)})


def django_scatter_svg(request):
    count, seed = get_params(request.GET)

    return render(
        request,
        "chartpdf/django_scatter.svg",
        {
            "points": [
                {"x": p["x"] * 800, "y": p["y"] * 600}
                for p in get_points(count, seed)
            ]
        },
        "image/svg+xml",
    )


def run_js(js) -> str:
    return subprocess.check_output(["node", "--input-type", "module"], input=js, text=True)


def index(request):
    count, seed = get_params(request.GET)

    points_ = get_points(count, seed)

    # D3 + jspybridge
    js_jspybridge = loader.render_to_string(
        "chartpdf/d3_jspybridge_svg.js", {"points": points_}
    )
    svg_jspybridge = javascript.eval_js(js_jspybridge)

    # D3 + node
    js_node = loader.render_to_string(
        "chartpdf/d3_node_svg.js", {"points": points_}
    )
    svg_node = run_js(js_node)

    return render(
        request,
        "chartpdf/index.html",
        {
            "d3_jspybridge_svg": svg_jspybridge, 
            "d3_node_svg": svg_node, 
            "count": count, 
            "seed": seed
        },
    )

chartpdf/templates/chartpdf/index.html
{% load static %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SVG generation demo</title>
</head>

<body>
    <h2>D3</h2>
    <div>
        <p>
            This graph is generated with the cannonical method: the SVG is
            build with d3 on the client side with data loaded from an AJAX
            call.
        </p>
        <svg class="cp-scatter" data-src="{% url 'chartpdf:api_get_points' %}?count={{ count }}&seed={{ seed }}"
            width="800" height="600" xmlns="http://www.w3.org/2000/svg">
        </svg>
    </div>

    <h2>Django template</h2>
    <div>
        <p>
            This graph is generated manually using the templating system of
            Django and loaded through a img tag. No JavaScript involved.
        </p>
        <img src="{% url 'chartpdf:django_scatter_svg' %}?count={{ count }}&seed={{ seed }}">
    </div>


    <h2>D3 JSPyBridge</h2>
    <div>
        <p>
            This graph is generated using d3 runned through JSPyBridge by
            Django and inserted using the templating system.
        </p>

        {{ d3_jspybridge_svg|safe }}
    </div>


    <h2>D3 Node</h2>
    <div>
        <p>
            This graph is generated using d3 runned through node by
            Django and inserted using the templating system.
        </p>

        {{ d3_node_svg|safe }}
    </div>

    {% compress js %}
    <script src="{% static 'chartpdf/d3@7.8.2.js' %}"></script>
    <script src="{% static 'chartpdf/cp_scatter.js' %}"></script>
    <script src="{% static 'chartpdf/index.js' %}"></script>
    {% endcompress %}
</body>

</html>